name: build-test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: mkdir -p path/to/artifact
      
      
    - name: Set up JDK 11.0.x
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        java-package: jdk
            
        
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
              
    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{job.status}}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        author_name: Aaron CI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

